name: getgather
networks:
  internal-net: {}

services:
  gateway:
    build:
      context: .
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal-net:
        aliases:
          - gateway.internal

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy:
    build:
      context: https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/gather-engineering/proxy-service.git
    env_file: .env.proxy
    expose:
      - "8889"
    networks:
      internal-net:
        aliases:
          - proxy.internal

volumes:
  caddy-data:
  caddy-config:
