# fly.toml app configuration file generated for mcp-gateway on 2025-09-16T13:29:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mcp-gateway'
primary_region = 'sjc'

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
