name: Prepare the back-end environment
description: Install Python and the dependencies
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Python dependencies
      shell: bash
      run: uv sync --all-extras --dev 

    - name: Install npm
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install npm dependencies
      shell: bash
      run: npm install

    - name: Setup podman
      if: ${{ env.CONTAINER_ENGINE == 'podman' }}
      shell: bash
      run: |
        if ! command -v podman &> /dev/null; then
          sudo apt update
          sudo apt -y install podman
        fi

        podman --version

        # Start podman rootful API service and make the socket accessible to the user
        sudo mkdir -p /run/podman
        sudo chmod 755 /run/podman
        sudo nohup podman system service --time=0 unix:///run/podman/podman.sock >/tmp/podman-api.log 2>&1 &
        sleep 2
        sudo chmod 666 /run/podman/podman.sock

    - name: Docker pull mcp-getgather image
      shell: bash
      if: ${{ env.CONTAINER_ENGINE == 'docker' }}
      run: docker image pull ghcr.io/mcp-getgather/mcp-getgather

    - name: Podman pull mcp-getgather image
      shell: bash
      if: ${{ env.CONTAINER_ENGINE == 'podman' }}
      run: sudo podman image pull ghcr.io/mcp-getgather/mcp-getgather