name: Prepare the back-end environment
description: Install Python and the dependencies
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Python dependencies
      shell: bash
      run: uv sync --all-extras --dev 

    - name: Install npm
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install npm dependencies
      shell: bash
      run: npm install

    - name: Pull mcp-getgather image
      shell: bash
      run: |
        docker image pull ghcr.io/mcp-getgather/mcp-getgather
        docker inspect ghcr.io/mcp-getgather/mcp-getgather
        docker inspect ghcr.io/mcp-getgather/mcp-getgather:latest
        DIGEST=$(docker inspect ghcr.io/mcp-getgather/mcp-getgather:latest | jq -r '.[0].Descriptor.digest')
        echo "Using mcp-getgather image digest: $DIGEST"
