name: Prepare the back-end environment
description: Install Python and the dependencies
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev
