name: Static Analysis

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  python-coding-style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/prepare-dev

      - name: Check formatting with Ruff
        run: uv run ruff format --check .

      - name: Lint with Ruff
        run: uv run ruff check .

  python-type-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/prepare-dev

      - name: Type check with pyright
        run: uv run pyright .

  frontend-format-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/prepare-dev

      - name: Format check with Prettier
        run: npm run format:check
