name: Static Analysis

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  python-coding-style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Check formatting with Ruff
        run: uv run ruff format --check .
      - name: Lint with Ruff
        run: uv run ruff check .

  python-type-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Type check with Ty
        run: uv run ty check .
